"""
lattice/vision_vocab.py - Telp's visual concept vocabulary (~900 concepts).

Used by the zero-shot namer (CLIP retrieval over labels). Expanding this list
directly expands what Telp can name in what it sees. Grouped for maintenance;
duplicates are harmless (deduped on load).
"""

VOCAB = [
    # ── people ──────────────────────────────────────────────────────
    "person", "face", "man", "woman", "child", "baby", "boy", "girl",
    "elderly person", "crowd", "couple", "family", "hand", "eye", "smile",
    "portrait", "selfie", "silhouette of a person",
    # roles
    "astronaut", "soldier", "athlete", "dancer", "chef", "doctor", "nurse",
    "police officer", "firefighter", "farmer", "fisherman", "teacher",
    "musician", "singer", "artist", "scientist", "engineer", "pilot",
    "warrior", "knight", "king", "queen", "wizard", "clown", "bride", "groom",
    "monk", "priest", "cowboy", "pirate", "ninja", "samurai", "viking",
    "cyclist", "runner", "swimmer", "climber", "skier", "surfer", "boxer",
    # ── mammals ─────────────────────────────────────────────────────
    "dog", "puppy", "cat", "kitten", "raccoon", "fox", "wolf", "bear",
    "polar bear", "panda", "koala", "horse", "pony", "donkey", "zebra",
    "cow", "bull", "ox", "buffalo", "bison", "sheep", "lamb", "goat",
    "pig", "boar", "rabbit", "hare", "squirrel", "chipmunk", "mouse",
    "rat", "hamster", "hedgehog", "bat", "deer", "elk", "moose", "reindeer",
    "antelope", "gazelle", "giraffe", "elephant", "rhinoceros", "hippopotamus",
    "lion", "tiger", "leopard", "cheetah", "jaguar", "cougar", "lynx",
    "monkey", "gorilla", "chimpanzee", "orangutan", "baboon", "lemur",
    "sloth", "anteater", "armadillo", "kangaroo", "opossum", "otter",
    "beaver", "badger", "skunk", "weasel", "ferret", "mole", "camel",
    "llama", "alpaca", "whale", "dolphin", "seal", "sea lion", "walrus",
    "manatee", "mongoose", "hyena", "meerkat",
    # ── birds ───────────────────────────────────────────────────────
    "bird", "eagle", "hawk", "falcon", "owl", "vulture", "crow", "raven",
    "magpie", "sparrow", "robin", "cardinal", "blue jay", "finch", "canary",
    "parrot", "macaw", "cockatoo", "parakeet", "pigeon", "dove", "seagull",
    "pelican", "albatross", "stork", "crane", "heron", "flamingo", "swan",
    "goose", "duck", "duckling", "chicken", "rooster", "hen", "chick",
    "turkey", "peacock", "pheasant", "quail", "ostrich", "emu", "penguin",
    "puffin", "kingfisher", "woodpecker", "hummingbird", "toucan",
    # ── reptiles / amphibians / fish / invertebrates ────────────────
    "snake", "cobra", "python", "viper", "lizard", "gecko", "iguana",
    "chameleon", "crocodile", "alligator", "turtle", "tortoise", "frog",
    "toad", "salamander", "newt", "fish", "goldfish", "koi", "shark",
    "ray", "eel", "seahorse", "salmon", "trout", "tuna", "swordfish",
    "octopus", "squid", "cuttlefish", "jellyfish", "starfish", "sea urchin",
    "coral", "crab", "lobster", "shrimp", "crayfish", "snail", "slug",
    "worm", "insect", "butterfly", "moth", "caterpillar", "bee", "wasp",
    "hornet", "ant", "termite", "beetle", "ladybug", "firefly", "dragonfly",
    "grasshopper", "cricket", "mantis", "cockroach", "fly", "mosquito",
    "spider", "tarantula", "scorpion", "centipede", "millipede",
    # ── fantasy / story creatures ───────────────────────────────────
    "dragon", "monster", "dinosaur", "tyrannosaurus", "unicorn", "mermaid",
    "fairy", "elf", "dwarf", "goblin", "troll", "ogre", "giant", "ghost",
    "skeleton", "zombie", "vampire", "werewolf", "alien", "robot", "cyborg",
    "griffin", "phoenix",
    # ── nature / landscape ──────────────────────────────────────────
    "tree", "oak tree", "pine tree", "palm tree", "willow", "birch",
    "bamboo", "cactus", "bush", "hedge", "forest", "jungle", "rainforest",
    "woods", "grass", "lawn", "meadow", "field", "prairie", "savanna",
    "flower", "rose", "tulip", "sunflower", "daisy", "lily", "orchid",
    "lavender", "lotus", "cherry blossom", "leaf", "fern", "moss", "vine",
    "ivy", "mushroom", "seed", "root", "branch", "log", "stump",
    "mountain", "mountain range", "hill", "cliff", "canyon", "valley",
    "gorge", "plateau", "volcano", "crater", "cave", "rock", "boulder",
    "stone", "pebble", "sand", "dune", "desert", "oasis", "beach", "coast",
    "shore", "island", "peninsula", "reef", "ocean", "sea", "wave", "surf",
    "lake", "pond", "river", "stream", "creek", "waterfall", "spring",
    "swamp", "marsh", "wetland", "glacier", "iceberg", "ice", "snow",
    "snowdrift", "frost", "sky", "cloud", "storm cloud", "rainbow",
    "lightning", "rain", "hail", "fog", "mist", "sunrise", "sunset", "sun",
    "moon", "full moon", "crescent moon", "stars", "night sky", "milky way",
    "aurora", "eclipse", "comet", "meteor", "planet", "galaxy", "nebula",
    "fire", "flame", "campfire", "bonfire", "smoke", "ember", "ash",
    "explosion", "dust", "mud", "puddle",
    # ── built world / places ────────────────────────────────────────
    "house", "cottage", "cabin", "hut", "mansion", "palace", "castle",
    "fortress", "tower", "lighthouse", "windmill", "watermill", "barn",
    "farm", "greenhouse", "stable", "shed", "garage", "warehouse",
    "factory", "power plant", "refinery", "mine", "quarry", "building",
    "skyscraper", "apartment building", "office building", "hotel",
    "hospital", "school", "university", "library", "museum", "theater",
    "cinema", "stadium", "arena", "gym", "church", "cathedral", "chapel",
    "mosque", "synagogue", "temple", "shrine", "pagoda", "monastery",
    "pyramid", "ruins", "monument", "statue", "fountain", "arch",
    "city", "skyline", "town", "village", "suburb", "street", "alley",
    "road", "highway", "intersection", "crosswalk", "sidewalk", "plaza",
    "square", "market", "bazaar", "shop", "store", "supermarket", "mall",
    "restaurant", "cafe", "bar", "pub", "bakery", "food stall",
    "gas station", "parking lot", "bridge", "tunnel", "dam", "canal",
    "harbor", "port", "dock", "pier", "marina", "airport", "runway",
    "train station", "platform", "bus stop", "railway", "train tracks",
    "fence", "gate", "wall", "brick wall", "door", "window", "balcony",
    "roof", "chimney", "stairs", "staircase", "escalator", "elevator",
    "hallway", "corridor", "courtyard", "garden", "park", "playground",
    "swimming pool", "hot tub", "tent", "campsite", "picnic table",
    "graveyard", "farmland", "vineyard", "orchard", "rice paddy",
    "construction site", "crane at a construction site", "scaffolding",
    # ── rooms / interior ────────────────────────────────────────────
    "room", "living room", "bedroom", "kitchen", "bathroom", "dining room",
    "office", "classroom", "laboratory", "workshop", "studio", "basement",
    "attic", "closet", "laundry room", "garage interior", "lobby",
    "waiting room", "conference room", "server room", "prison cell",
    # ── furniture / household ───────────────────────────────────────
    "table", "desk", "chair", "armchair", "sofa", "couch", "bench", "stool",
    "bed", "bunk bed", "crib", "mattress", "pillow", "blanket", "quilt",
    "curtain", "blinds", "carpet", "rug", "shelf", "bookshelf", "cabinet",
    "cupboard", "drawer", "dresser", "wardrobe", "mirror", "lamp",
    "chandelier", "candle", "lantern", "fireplace", "radiator", "fan",
    "air conditioner", "heater", "vase", "flowerpot", "picture frame",
    "painting", "poster", "wallpaper", "clock", "wall clock", "alarm clock",
    "doormat", "coat rack", "umbrella stand", "trash can", "recycling bin",
    "bucket", "basket", "laundry basket", "hamper", "ladder", "toolbox",
    "broom", "mop", "vacuum cleaner", "iron", "ironing board", "sewing machine",
    # ── kitchen / food ──────────────────────────────────────────────
    "food", "meal", "breakfast", "dinner", "plate", "bowl", "cup", "mug",
    "glass", "wine glass", "bottle", "jar", "can", "carton", "pot", "pan",
    "frying pan", "kettle", "teapot", "coffee maker", "espresso machine",
    "toaster", "microwave", "oven", "stove", "grill", "barbecue",
    "refrigerator", "freezer", "dishwasher", "sink", "faucet", "cutting board",
    "knife", "fork", "spoon", "chopsticks", "ladle", "whisk", "spatula",
    "blender", "mixer", "scale", "apron", "napkin", "tablecloth",
    "bread", "baguette", "toast", "sandwich", "burger", "hot dog", "pizza",
    "pasta", "spaghetti", "noodles", "ramen", "rice", "sushi", "dumplings",
    "taco", "burrito", "salad", "soup", "stew", "curry", "steak", "chicken dish",
    "fried chicken", "fish dish", "seafood", "egg", "fried egg", "omelette",
    "pancakes", "waffles", "cereal", "porridge", "cheese", "butter", "yogurt",
    "milk", "cream", "ice cream", "cake", "cupcake", "pie", "tart", "donut",
    "cookie", "brownie", "chocolate", "candy", "lollipop", "popcorn", "chips",
    "fries", "pretzel", "muffin", "croissant", "bagel", "jam", "honey",
    "fruit", "apple", "banana", "orange", "lemon", "lime", "grapefruit",
    "grapes", "strawberry", "blueberry", "raspberry", "cherry", "peach",
    "pear", "plum", "apricot", "mango", "pineapple", "watermelon", "melon",
    "kiwi", "papaya", "coconut", "avocado", "pomegranate", "fig", "date fruit",
    "vegetable", "tomato", "potato", "carrot", "onion", "garlic", "pepper",
    "chili", "cucumber", "zucchini", "eggplant", "broccoli", "cauliflower",
    "cabbage", "lettuce", "spinach", "kale", "celery", "asparagus", "corn",
    "peas", "beans", "pumpkin", "squash", "radish", "beet", "turnip",
    "coffee", "tea", "juice", "smoothie", "soda", "water bottle", "beer",
    "wine", "whiskey", "cocktail", "champagne",
    # ── clothing ────────────────────────────────────────────────────
    "clothing", "shirt", "t-shirt", "blouse", "sweater", "hoodie", "jacket",
    "coat", "raincoat", "vest", "suit", "tuxedo", "dress", "gown", "skirt",
    "pants", "jeans", "shorts", "leggings", "pajamas", "robe", "uniform",
    "armor", "cloak", "cape", "scarf", "shawl", "tie", "bow tie", "belt",
    "gloves", "mittens", "hat", "cap", "beanie", "beret", "helmet", "crown",
    "hood", "mask", "sunglasses", "glasses", "watch", "bracelet", "necklace",
    "earrings", "ring", "brooch", "shoe", "sneakers", "boots", "sandals",
    "high heels", "slippers", "socks", "backpack", "bag", "handbag", "purse",
    "wallet", "suitcase", "briefcase", "umbrella",
    # ── vehicles ────────────────────────────────────────────────────
    "car", "sports car", "race car", "taxi", "police car", "ambulance",
    "fire truck", "truck", "pickup truck", "semi truck", "van", "minivan",
    "bus", "school bus", "trolley", "tram", "train", "steam locomotive",
    "subway", "monorail", "bicycle", "mountain bike", "tricycle", "scooter",
    "motorcycle", "moped", "skateboard", "roller skates", "wheelchair",
    "stroller", "shopping cart", "wagon", "carriage", "chariot", "sled",
    "sleigh", "snowmobile", "tractor", "bulldozer", "excavator", "forklift",
    "crane truck", "cement mixer", "garbage truck", "tank", "jeep",
    "golf cart", "go-kart", "airplane", "jet", "fighter jet", "biplane",
    "seaplane", "glider", "helicopter", "drone", "blimp", "hot air balloon",
    "rocket", "spaceship", "space station", "satellite", "boat", "sailboat",
    "yacht", "speedboat", "rowboat", "canoe", "kayak", "raft", "gondola",
    "ferry", "cruise ship", "cargo ship", "container ship", "fishing boat",
    "submarine", "jet ski", "surfboard", "paddleboard",
    # ── technology ──────────────────────────────────────────────────
    "phone", "smartphone", "telephone", "computer", "laptop", "desktop computer",
    "monitor", "screen", "keyboard", "mouse", "trackpad", "tablet", "e-reader",
    "television", "remote control", "game console", "game controller",
    "joystick", "arcade machine", "camera", "video camera", "webcam",
    "tripod", "microphone", "headphones", "earbuds", "speaker", "radio",
    "record player", "vinyl record", "cassette", "cd", "projector",
    "printer", "scanner", "photocopier", "fax machine", "calculator",
    "typewriter", "hard drive", "usb drive", "circuit board", "microchip",
    "wires", "cables", "battery", "charger", "power outlet", "light bulb",
    "flashlight", "solar panel", "wind turbine", "antenna", "satellite dish",
    "telescope", "microscope", "binoculars", "compass", "thermometer",
    "barometer", "stopwatch", "hourglass", "scale instrument", "robot arm",
    "3d printer", "virtual reality headset", "smartwatch",
    # ── tools / equipment ───────────────────────────────────────────
    "tool", "hammer", "screwdriver", "wrench", "pliers", "saw", "handsaw",
    "chainsaw", "drill", "axe", "hatchet", "chisel", "file tool", "sandpaper",
    "tape measure", "level tool", "clamp", "vise", "anvil", "shovel",
    "spade", "rake", "hoe", "pitchfork", "wheelbarrow", "watering can",
    "garden hose", "lawn mower", "hedge trimmer", "scissors", "shears",
    "needle", "thread", "rope", "chain", "hook", "pulley", "nail", "screw",
    "bolt", "nut hardware", "gear", "spring", "magnet", "padlock", "key",
    "keychain", "handcuffs", "fishing rod", "fishing net", "trap",
    "matches", "lighter", "first aid kit", "bandage", "syringe", "stethoscope",
    "pill bottle", "medicine", "crutches", "cast",
    # ── weapons ─────────────────────────────────────────────────────
    "sword", "dagger", "spear", "lance", "axe weapon", "mace", "hammer weapon",
    "bow and arrow", "crossbow", "shield", "gun", "pistol", "rifle", "cannon",
    "catapult", "grenade", "missile", "torpedo", "whip", "slingshot",
    # ── music / art / games ─────────────────────────────────────────
    "guitar", "electric guitar", "bass guitar", "violin", "cello", "harp",
    "piano", "grand piano", "organ", "accordion", "flute", "clarinet",
    "saxophone", "trumpet", "trombone", "tuba", "harmonica", "banjo",
    "ukulele", "drum", "drum kit", "cymbals", "xylophone", "tambourine",
    "maracas", "bagpipes", "sheet music", "music notes", "conductor",
    "paintbrush", "palette", "easel", "canvas", "sculpture", "pottery",
    "clay", "origami", "knitting", "embroidery", "mosaic", "stained glass",
    "graffiti", "chalk drawing", "sketch", "drawing", "illustration",
    "chess board", "chess pieces", "checkers", "backgammon", "dice",
    "playing cards", "poker chips", "dominoes", "puzzle", "jigsaw puzzle",
    "crossword", "board game", "dartboard", "billiards", "bowling",
    "ball", "soccer ball", "basketball", "football", "baseball", "tennis ball",
    "volleyball", "golf ball", "rugby ball", "ping pong", "badminton",
    "tennis racket", "baseball bat", "golf club", "hockey stick", "puck",
    "goal net", "basketball hoop", "trampoline", "seesaw", "swing", "slide",
    "kite", "frisbee", "boomerang", "yo-yo", "balloon", "teddy bear",
    "doll", "action figure", "toy car", "toy train", "building blocks",
    "lego", "marbles", "spinning top", "rocking horse", "jack-o-lantern",
    "christmas tree", "christmas ornament", "wreath", "fireworks", "confetti",
    "pinata", "birthday cake", "gift", "present", "ribbon", "trophy",
    "medal", "flag", "banner",
    # ── documents / media / symbols ─────────────────────────────────
    "book", "open book", "notebook", "journal", "diary", "magazine",
    "newspaper", "comic book", "manga", "map", "globe", "atlas", "scroll",
    "envelope", "letter", "postcard", "stamp", "document", "certificate",
    "diploma", "contract", "receipt", "ticket", "passport", "id card",
    "credit card", "money", "cash", "coins", "gold bars", "treasure chest",
    "piggy bank", "sign", "street sign", "stop sign", "billboard",
    "neon sign", "text", "handwriting", "calligraphy", "alphabet",
    "numbers", "mathematical formula", "chart", "graph", "diagram",
    "blueprint", "calendar", "screenshot", "logo", "emblem", "barcode",
    "qr code", "pen", "pencil", "marker", "crayon", "highlighter",
    "eraser", "ruler", "stapler", "paperclip", "pushpin", "tape",
    "glue", "folder", "binder", "clipboard", "whiteboard", "blackboard",
    "chalk", "podium", "microphone stand",
    # ── scenes / styles / media types ───────────────────────────────
    "cartoon", "animation", "anime", "video game", "pixel art", "3d render",
    "landscape", "seascape", "cityscape", "night scene", "underwater scene",
    "aerial view", "close-up photo", "macro photo", "panorama",
    "black and white photo", "vintage photo", "microscope image", "x-ray",
    "mri scan", "ultrasound", "thermal image", "infrared image",
    "long exposure photo", "time lapse", "double exposure", "abstract art",
    "watercolor painting", "oil painting", "still life", "collage",
    "wedding", "party", "concert", "parade", "festival", "protest",
    "graduation", "sports game", "race", "marathon", "competition",
    "interview", "meeting", "lecture", "surgery", "experiment",
]
